# docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - aisalesman_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eeriecast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: webtest123

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8012:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: EeriecastDjango.settings
      DEBUG: True
      DB_NAME: eeriecast
      DB_USER: postgres
      DB_PASSWORD: webtest123
      DB_HOST: db
      DB_PORT: 5432
      REACT_URL: http://localhost:5173
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      STRIPE_SECRET_KEY: sk_test_51NgsNSDZQqr6bWzenpD5ekAndKhlkwaPc6hRJcbo8QYExHMomDd1iW6FKPdAUKnIRjH6gSV6zsrzPe6sBgLtvdPg00UCXNbn9o
      STRIPE_PUBLIC_KEY: pk_test_51NgsNSDZQqr6bWzeMdhzAHgTAEntrvf1CYPyXTuuiUwJg5Tw23MzLNTN2lnvsExdCgwLNdFUGIxB4GDUsWTP8mHP00IQ9YjptB
      STRIPE_WEBHOOK_SECRET: whsec_jCyj9WBHGc8ODVOtwc9o7VA4PJLoM91o
      STRIPE_MONTHLY_PRICE_ID: price_1QVkCFDZQqr6bWze584rDEz0

  celery_worker:
    build: .
    command: sh -c "python manage.py migrate && celery -A EeriecastDjango worker -l info"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: EeriecastDjango.settings
      DEBUG: True
      DB_NAME: eeriecast
      DB_USER: postgres
      DB_PASSWORD: webtest123
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery_beat:
    build: .
    command: sh -c "python manage.py migrate && celery -A EeriecastDjango beat -l info"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: EeriecastDjango.settings
      DEBUG: True
      DB_NAME: eeriecast
      DB_USER: postgres
      DB_PASSWORD: webtest123
      DB_HOST: db
      DB_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

volumes:
  aisalesman_postgres_data:
